#!/usr/bin/env python3
"""
JetLagPro Trip Signature Verification Script

Verifies HMAC-SHA256 cryptographic signatures on trip records to ensure
they were generated by the authentic iOS app and have not been tampered with.

Usage:
    python verify_trip_signatures.py --trips trips.json --secret-key YOUR_SECRET

Requirements:
    - Python 3.6+
    - No external dependencies (uses only standard library)

Security Note:
    The secret key is embedded in the iOS app and is used for signature verification.
    This script requires the secret key to verify signatures.

Author: Steven Schram PhD, DC, LAc
License: MIT
Repository: https://github.com/SBSchram/jetlagpro-website
"""

import json
import hmac
import hashlib
import sys
from typing import Dict, List, Optional


def compute_signature(trip_data: Dict, secret_key: str) -> str:
    """
    Compute HMAC-SHA256 signature for a trip record.
    
    The signature is computed over a canonical representation of the trip data:
    - tripId|userId|departureAirport|arrivalAirport|departureTime|arrivalTime|points
    
    Args:
        trip_data: Dictionary containing trip fields
        secret_key: Secret key for HMAC computation
    
    Returns:
        Hexadecimal string of the HMAC-SHA256 signature
    """
    # Extract fields in canonical order
    fields = [
        trip_data.get('tripId', ''),
        trip_data.get('userId', ''),
        trip_data.get('departureAirport', ''),
        trip_data.get('arrivalAirport', ''),
        str(trip_data.get('departureTime', '')),
        str(trip_data.get('arrivalTime', '')),
        str(trip_data.get('points', ''))
    ]
    
    # Create canonical string (pipe-separated)
    canonical = '|'.join(fields)
    
    # Compute HMAC-SHA256
    signature = hmac.new(
        secret_key.encode('utf-8'),
        canonical.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()
    
    return signature


def verify_trip_signature(trip: Dict, secret_key: str) -> Dict:
    """
    Verify the signature of a single trip record.
    
    Args:
        trip: Trip record dictionary
        secret_key: Secret key for HMAC verification
    
    Returns:
        Dictionary with verification result:
        {
            'tripId': str,
            'valid': bool,
            'reason': str (if invalid),
            'expected_signature': str (if invalid),
            'actual_signature': str
        }
    """
    trip_id = trip.get('tripId', 'unknown')
    actual_signature = trip.get('hmacSignature', '')
    
    result = {
        'tripId': trip_id,
        'actual_signature': actual_signature
    }
    
    # Check if signature field exists
    if not actual_signature:
        result['valid'] = False
        result['reason'] = 'Missing signature (legacy trip)'
        return result
    
    # Check if it's a test trip (skip verification)
    if trip.get('isTest', False):
        result['valid'] = True
        result['reason'] = 'Test trip (signature not verified)'
        return result
    
    # Compute expected signature
    expected_signature = compute_signature(trip, secret_key)
    result['expected_signature'] = expected_signature
    
    # Compare signatures (constant-time comparison to prevent timing attacks)
    if hmac.compare_digest(actual_signature, expected_signature):
        result['valid'] = True
    else:
        result['valid'] = False
        result['reason'] = 'Signature mismatch (possible tampering)'
    
    return result


def load_trips(trips_path: str) -> List[Dict]:
    """Load trip records from JSON file."""
    print(f"Loading trips from: {trips_path}")
    
    with open(trips_path, 'r') as f:
        data = json.load(f)
    
    # Handle Firestore REST API format
    if 'documents' in data:
        trips = []
        for doc in data['documents']:
            trip = {}
            if 'fields' in doc:
                # Extract fields from Firestore format
                for key, value in doc['fields'].items():
                    if 'stringValue' in value:
                        trip[key] = value['stringValue']
                    elif 'integerValue' in value:
                        trip[key] = int(value['integerValue'])
                    elif 'doubleValue' in value:
                        trip[key] = float(value['doubleValue'])
                    elif 'booleanValue' in value:
                        trip[key] = value['booleanValue']
                    elif 'timestampValue' in value:
                        trip[key] = value['timestampValue']
            trips.append(trip)
    elif isinstance(data, list):
        trips = data
    else:
        trips = [data]
    
    print(f"  Loaded {len(trips)} trip records")
    return trips


def verify_all_trips(trips: List[Dict], secret_key: str) -> Dict:
    """
    Verify signatures for all trips.
    
    Returns:
        Report dictionary with verification results
    """
    print("\nVerifying trip signatures...")
    
    results = []
    valid_count = 0
    invalid_count = 0
    legacy_count = 0
    test_count = 0
    
    for trip in trips:
        result = verify_trip_signature(trip, secret_key)
        results.append(result)
        
        if result['valid']:
            if 'Test trip' in result.get('reason', ''):
                test_count += 1
            else:
                valid_count += 1
        else:
            if 'legacy' in result.get('reason', '').lower():
                legacy_count += 1
            else:
                invalid_count += 1
    
    report = {
        'total_trips': len(trips),
        'valid_signatures': valid_count,
        'invalid_signatures': invalid_count,
        'legacy_trips': legacy_count,
        'test_trips': test_count,
        'results': results
    }
    
    return report


def print_report(report: Dict, verbose: bool = False) -> int:
    """
    Print verification report.
    Returns exit code: 0 if all valid, 1 if invalid signatures found.
    """
    print("\n" + "="*60)
    print("TRIP SIGNATURE VERIFICATION REPORT")
    print("="*60)
    print(f"Total trips: {report['total_trips']}")
    print(f"Valid signatures: {report['valid_signatures']}")
    print(f"Invalid signatures: {report['invalid_signatures']}")
    print(f"Legacy trips (no signature): {report['legacy_trips']}")
    print(f"Test trips (not verified): {report['test_trips']}")
    print("="*60)
    
    # Show invalid signatures
    if report['invalid_signatures'] > 0:
        print("\n✗ INVALID SIGNATURES DETECTED:")
        for result in report['results']:
            if not result['valid'] and 'legacy' not in result.get('reason', '').lower():
                print(f"\n  Trip ID: {result['tripId']}")
                print(f"  Reason: {result['reason']}")
                if verbose:
                    print(f"  Expected: {result.get('expected_signature', 'N/A')}")
                    print(f"  Actual:   {result['actual_signature']}")
    
    # Summary
    print("\n" + "="*60)
    if report['invalid_signatures'] == 0:
        print("✓ VERIFICATION PASSED")
        print("All trip signatures are valid.")
        print("No evidence of tampering detected.")
        return 0
    else:
        print("✗ VERIFICATION FAILED")
        print(f"{report['invalid_signatures']} trip(s) have invalid signatures.")
        print("Possible tampering or data corruption detected.")
        return 1


def main():
    """Main verification workflow."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Verify JetLagPro trip cryptographic signatures',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  # Download trip data from Firestore
  curl -s "https://firestore.googleapis.com/v1/projects/jetlagpro-research/databases/(default)/documents/trips?pageSize=1000" -o trips.json
  
  # Verify signatures
  python verify_trip_signatures.py --trips trips.json --secret-key YOUR_SECRET_KEY
  
  # Verbose output
  python verify_trip_signatures.py --trips trips.json --secret-key YOUR_SECRET_KEY --verbose

Security Note:
  The secret key is required for verification. Contact the study authors
  if you need access to the key for independent verification.
        """
    )
    
    parser.add_argument(
        '--trips',
        required=True,
        help='Path to trips JSON file'
    )
    parser.add_argument(
        '--secret-key',
        required=True,
        help='Secret key for HMAC verification'
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Show detailed signature information'
    )
    
    args = parser.parse_args()
    
    # Load trips
    try:
        trips = load_trips(args.trips)
    except FileNotFoundError:
        print(f"ERROR: Trips file not found: {args.trips}")
        return 1
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in trips file: {e}")
        return 1
    except Exception as e:
        print(f"ERROR: Failed to load trips: {e}")
        return 1
    
    # Verify all trips
    report = verify_all_trips(trips, args.secret_key)
    
    # Print report and exit
    exit_code = print_report(report, verbose=args.verbose)
    return exit_code


if __name__ == '__main__':
    sys.exit(main())

